spring.application.name=ComplaintManagement

spring.data.rest.base-path=/api

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/complaintmanagement}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=9090


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME:YOUR_GMAIL@gmail.com}

spring.mail.password=${MAIL_PASSWORD:YOUR_APP_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
